# Generated by Django 3.0.3 on 2020-02-15 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.AddField(
            model_name='book',
            name='title2',
            field=models.CharField(default=' book', max_length=300),
        ),
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 16, 23, 50, 8, 607496)),
        ),
    ]
