# Generated by Django 3.0.3 on 2020-02-15 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200215_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title2',
        ),
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='books_pdf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 17, 0, 8, 34, 204584)),
        ),
    ]
