# Generated by Django 3.0.4 on 2020-05-10 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200216_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookrenthistory',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'История скачивания книг'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='inboxmessages',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Полученные сообщения'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_amount',
            field=models.IntegerField(verbose_name='Колличество книг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='books_pdf', verbose_name='Загрузите книгу'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='About book', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book.png', upload_to='books_pics', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(verbose_name='Колличество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 9, 14, 42, 10, 581447)),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
    ]
